# Generated by Django 5.2 on 2025-06-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
