# Generated by Django 5.2 on 2025-06-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_posts', '0002_prompt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
