# Generated by Django 5.2 on 2025-06-07 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_posts', '0003_alter_prompt_slug_alter_topic_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='prompt',
            table_comment='Table for storing prompts with their details, including author, topic, and image.',
        ),
        migrations.AlterModelTableComment(
            name='topic',
            table_comment='Table for storing topics with their details, including name and description.',
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['content'], name='prompt_content_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['author'], name='prompt_author_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['topic'], name='prompt_topic_idx'),
        ),
    ]
